name: sa_firebase_auth_lego
description: "lego is all you need"
#publish_to: 'none'
#repository: https://github.com/melodysdreamj/lego

version: 1.0.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: #@add
  gap: #@add
  june_flow_util: #@add
  styled_widget: #@add
  modal_bottom_sheet: #@add
  keyboard_attachable: #@add
  flutter_zoom_drawer: #@add
  flutter_screenutil:
  bot_toast:
  firebase_core:
  firebase_auth: ^4.16.0
  package_info_plus:
  google_sign_in: ^6.2.1
  flutter_fgbg:
  easy_event_bus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  screenutil_lego: #@add
  bot_toast_lego: #@add
  widget_binding_lego: #@add
  firebase_core_lego: #@add
  sa_data_class_lego:
  package_info_plus_lego:
  sa_fgbg_listener_lego:
  flutter_fgbg_lego:
  listener_lego: #@add
  sa_listener_lego:

flutter:
  assets:
    - assets/lego/sa_firebase_auth_lego/
  uses-material-design: true

topics:
  - lego